import type { Metadata } from "next";
import Sidebar from "@/components/Sidebar";
import Navbar from "@/components/Navbar";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function DashboardLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
     <div className="min-h-screen flex flex-col">
        <Navbar/>
        <div className="flex h-screen">
        <Sidebar/>
        <div className="ml-56 flex-1 mt-16">
        {children}
        </div>
        </div>
      </div>
  );
}
